### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by 2014gaokao** [dangweili/pedestrian-attribute-recognition-pytorch#13]
after I run  sh script/experiment/train.sh

Traceback (most recent call last):
  File "./script/experiment/train_deepmar_resnet50.py", line 18, in <module>
    from baseline.dataset import add_transforms
ImportError: No module named baseline.dataset

baseline.dataset exists, it puzzles me

**Comment by dangweili** [comment]
maybe you can put this code in the start of train_deepmar_resnet50.py
`
sys.path.append(os.getcwd())
`

**Comment by 2014gaokao** [comment]
Thank you! I use the second version of RAP dataset and get result as follows
Label-based evaluation:
mA: 0.7498
Instance-based evaluation:
Acc: 0.7099, Prec: 0.8252, Rec: 0.8114, F1: 0.8182
I have no idea if it is a good result and does this research area mature now? I wonder if i can do some improvments such as using gcn to model label depedencies etc.
