### ISSUE TITLE
Can we train the model with all datasets?

### ISSUE THREAD

**Issue by DeepTiming** [dangweili/pedestrian-attribute-recognition-pytorch#14]

**Comment by dangweili** [comment]
Now different datasets have different types of attributes. If you want to train multiple attributes jointly, I think you should code all the attributes in a uniformed format.

**Comment by DeepTiming** [comment]
get it! thank you very much!

**Comment by kclch** [comment]
@DeepTiming How do you get the overall dataset?thank you
