### ISSUE TITLE
Directly resize input image to 224x224 ?

### ISSUE THREAD

**Issue by handong1587** [dangweili/pedestrian-attribute-recognition-pytorch#18]
I can see in your paper you first resize images to 256x256 then crop 227xx227: [paper](https://www.researchgate.net/publication/283484818_Multi-attribute_Learning_for_Pedestrian_Attribute_Recognition_in_Surveillance_Scenarios)

` In addition, the images are resized to 256×256 first.  After that, they are randomly mirrored and cropped to 227×227 to add the training data`

However in your code you directly resize input images to 224x224. 

Code snippet from `./script/experiment/train.sh`:

```
python ./script/experiment/train_deepmar_resnet50.py \
    ....
    --resize="(224,224)" \
```

Did I miss anything? Because I thought random-crop might work better in some classification tasks.

**Comment by dangweili** [comment]
@handong1587 For resnet50, I didn't try data augmentation of random crop. I also agree with you that random-crop might work better. Maybe you can try it.

**Comment by handong1587** [comment]
Thanks for your reply!

**Comment by kclch** [comment]
@I would like to ask if I use  data augmentation of random crop, how should I do it in "./script/experiment/train.sh:"
Python ./script/experiment/train_deepmar_resnet50.py \
     ....
     --resize="(224,224)" \"
How to amend? Thank you

**Comment by dangweili** [comment]
It does not support random crop now. It is easy to extend the random crop augmentation. You can add the config parameter and implement it in image transform function at line 201-205 and 225-228 at script/experiment/train_deepmar_resnet50.py

**Comment by kclch** [comment]
@dangweili Hello, I tried random cropping while training, by modifying the"script/experiment/train_deepmar_resnet50.py" at line 201-205 and 225-228:
![image](https://user-images.githubusercontent.com/39482063/58948814-929f6880-87bd-11e9-81e7-5c7742b7bafc.png)
![image](https://user-images.githubusercontent.com/39482063/58948875-bbbff900-87bd-11e9-8148-7bcfc889425d.png),but I got the error:
![image](https://user-images.githubusercontent.com/39482063/58948978-f3c73c00-87bd-11e9-9472-004887d08d67.png)Please guide me
