### ISSUE TITLE
problem in running demo.py

### ISSUE THREAD

**Issue by GayatriPurandharT** [dangweili/pedestrian-attribute-recognition-pytorch#25]
Hello @dangweili ,
I converted py2 files to py3 and am using PyTorch 0.3.1 as specified. 
I get a Runtime error (screenshot is attached.)

![Screenshot from 2019-09-27 00-14-22](https://user-images.githubusercontent.com/37131394/65709789-de06bb00-e0bb-11e9-84a5-36af29fd7c1a.png)

Can you please guide me if I'm missing something.
Thanks a lot.

**Comment by GayatriPurandharT** [comment]
That was due to an incorrect environment. Now it runs fine with python 3.6 and PyTorch 1.2.0

**Comment by kHarshit** [comment]
***Update:** Solved it #28*

Hi @GayatriPurandharT, Can you please suggest the changes required to run this model in python3. So far, I've changed `cpickle` instances to `pickle` and added binary model to reading and writing operations `rb`.

**Comment by GayatriPurandharT** [comment]
Hey I first used python2-python3 converter, you can install using `pip install 2to3`
Then there are small changes to be done with using tensor.data instead of tensor.item().
With pytorch 1.2.0, it should work fine. Good luck.

**Comment by kHarshit** [comment]
Thank you @GayatriPurandharT
