### ISSUE TITLE
How can I make a .mat file for my own dataset to train the DeepMAR model?

### ISSUE THREAD

**Issue by GayatriPurandharT** [dangweili/pedestrian-attribute-recognition-pytorch#27]
I see that ./dataset/peta/ contains  PETA.mat file. This file contains mapping between images and labels. I also understand that script/dataset/transform_peta.py converts .mat file to .pkl. I need to know how to generate .mat file for my own images. 
Thank you.

**Comment by dangweili** [comment]
You can  generate the pkl file directly for your own dataset for training.  The mat file is not necessary.

**Comment by GayatriPurandharT** [comment]
Thank you, I understand now.
