### ISSUE TITLE
The performance of the model on RAP datasets

### ISSUE THREAD

**Issue by trikim** [dangweili/pedestrian-attribute-recognition-pytorch#8]
Have you tested the performance of trained model on RAP dataset?  I have trained the first 51 attributes of RAP dataset with ResNet50, but the result is not good enough compared to the paper. the result is as follow:
mA: 0.7549
Acc: 0.5831, Prec: 0.7393, Rec: 0.7097, F1: 0.7242

**Comment by trikim** [comment]
sorry to disturb you, I finally found that I made a mistake in the data pre-processing. Now I get a good result:
mA: 0.7525
Acc: 0.6588, Prec: 0.8040, Rec: 0.7637, F1: 0.7833
Thanks to the great repository.

**Comment by dangweili** [comment]
@trikim Got it~

**Comment by nakill** [comment]
@trikim Can you share me  RAP dataset

**Comment by daiwc** [comment]
> @trikim Can you share me RAP dataset vs pretrained model
> Thanks.

if you got rap dataset, please share with me !!! thanks a lot!
